refactor: Give root skill a 3 turn cooldown
Battle-Modders/mod-reforged pull request #128
Opened 2023-03-31 22:42 UTC by Uberbagel

2023-04-04 23:26 UTC, LordMidas requested changes

2023-04-04 23:26 UTC, LordMidas commented on mod_reforged/hooks/skills/actives/root_skill.nut
> +::mods_hookExactClass("skills/actives/root_skill", function(o) {
This is not the correct way. Look at our hook on rally_skill to see how to implement a better cooldown system. Then when you add the skill to the entity you specify the cooldown via `::MSU.new` (for this see how we add rally_skill to brigand_leader)

2023-04-05 11:10 UTC, Uberbagel commented
I just pulled the code directly from PTR. I'll let tech handle it and focus on getting ahead on design instead.

2023-04-06 05:41 UTC, LordMidas commented
> I just pulled the code directly from PTR. I'll let tech handle it and focus on getting ahead on design instead.

Yes that's fine. I'll do it.

2023-04-06 05:46 UTC, closed without merging