New armors
Battle-Modders/mod-reforged pull request #134
Opened 2023-05-01 00:06 UTC by Uberbagel

complete with metadata

2023-07-23 22:30 UTC, Darxo requested changes

2023-07-23 22:30 UTC, Darxo commented on mod_reforged/hooks/entity/world/attached_location/fortified_outpost_location.nut
> +							S = "weapons/rf_battle_axe"
This addition is outside of the scope of this PR. It should be added in its own branch.

2023-07-23 22:30 UTC, Darxo commented on mod_reforged/hooks/entity/world/attached_location/fortified_outpost_location.nut
> +							S = "weapons/rf_reinforced_wooden_poleflail"
This addition is outside of the scope of this PR. It should be added in its own branch.

2023-07-23 22:30 UTC, Darxo commented on mod_reforged/hooks/entity/world/attached_location/ore_smelters_location.nut
> +							S = "weapons/rf_battle_axe"
This addition is outside of the scope of this PR. It should be added in its own branch.

2023-07-23 22:30 UTC, Darxo commented on mod_reforged/hooks/entity/world/attached_location/ore_smelters_location.nut
> +							S = "weapons/rf_greatsword"
This addition is outside of the scope of this PR. It should be added in its own branch.

2023-07-23 22:30 UTC, Darxo commented on mod_reforged/hooks/entity/world/attached_location/ore_smelters_location.nut
> +							S = "weapons/rf_kriegsmesser"
This addition is outside of the scope of this PR. It should be added in its own branch.

2023-07-23 22:30 UTC, Darxo commented on mod_reforged/hooks/entity/world/attached_location/ore_smelters_location.nut
> +							S = "weapons/rf_swordstaff"
This addition is outside of the scope of this PR. It should be added in its own branch.

2023-07-23 22:30 UTC, Darxo commented on mod_reforged/hooks/entity/world/attached_location/stone_watchtower_location.nut
> +							S = "weapons/rf_reinforced_wooden_poleflail"
This addition is outside of the scope of this PR. It should be added in its own branch.

2023-07-23 22:30 UTC, Darxo commented on mod_reforged/hooks/entity/world/attached_location/surface_iron_vein_location.nut
> +			case "building.weaponsmith":
This addition is outside of the scope of this PR. It should be added in its own branch.

2023-07-23 22:30 UTC, Darxo commented on scripts/items/armor/rf_breastplate.nut
> +		this.m.SlotType = this.Const.ItemSlot.Body;
replace `this.Const` with `::Const`.
This is the first occurence that I saw and I will not mark all the other ones

2023-07-23 22:30 UTC, Darxo commented on scripts/items/helmets/named/named_conical_billed_helmet.nut
What is the purpose of these empty files?
Even if you plan on adding named versions for them later, these files should only then be created and filled instead of you adding placeholder for them now.

I will not comment on all the other empty named files that are also included but the above is true for them aswell.

2023-07-23 22:30 UTC, Darxo commented on unpacked_brushes/rf_entity/metadata.xml
I'm unsure whether `rf_entity` is the best folder name for these armor/helmets and whether `rf_entity.png` is the right name for its combined image.

I would rather try to separate equipments from the other entity stuff and have one folder for **equipment** and one for **entities**. 
But lets get a third opinion on this matter atleast.

2023-07-25 01:03 UTC, Uberbagel commented on scripts/items/helmets/named/named_conical_billed_helmet.nut
This was a mistake. That commit was meant to be removing them, but was adding them instead.

2023-08-29 22:25 UTC, LordMidas approved these changes
Replace all instances of `this.Const` with `::Const` and then merge.

2023-08-30 23:59 UTC, Darxo requested changes

2023-08-30 23:59 UTC, Darxo commented on unpacked_brushes/rf_entity/entity/helmets/rf_padded_skull_cap_with_rondels_dead.png
This helmet has a face inside.

2023-09-09 22:14 UTC, LordMidas commented on unpacked_brushes/rf_entity/metadata.xml
`entity` is the brush name vanilla uses for these things (to be exact there are several `entity` brushes in vanilla e.g. `entity_0`, `entity_1` etc.). So `rf_entity` is in line with that. But I don't like that as it isn't clear at all from the brush name what is in the brush. In my opinion we should have separate brushes: `armor`, `helmet`, `weapons`, `shields` etc. for each different kind of thing. Get @Enduriel's opinion on this.

2023-09-11 20:12 UTC, LordMidas commented on unpacked_brushes/rf_entity/metadata.xml
Enduriel (and Taro) said that we should keep a single brush and add comments within the file to organize it.

2023-09-11 20:16 UTC, Darxo approved these changes

2023-09-11 21:00 UTC, merged