feat: expand and rework bandit faction
Battle-Modders/mod-reforged pull request #153
Opened 2023-08-29 22:38 UTC by Uberbagel

2023-08-29 23:30 UTC, LordMidas requested changes

2023-08-29 23:30 UTC, LordMidas commented on mod_reforged/hooks/config/spawnlist_master.nut
> +::Const.World.Spawn.Troops.HedgeKnight.Strength = 45;
You set only the Strength, but not the Cost for HedgeKnight, Swordmaster, MasterArcher. Please set the Cost too.

2023-08-29 23:30 UTC, LordMidas commented on mod_reforged/hooks/entity/tactical/enemies/bandit_poacher.nut
> +		// this.m.Skills.add(::new("scripts/skills/actives/rotation")); // Replaced with perk
You say rotation is replaced with perk but there is no Rotation perk on this character.

2023-08-29 23:30 UTC, LordMidas commented on scripts/!mods_preload/mod_reforged.nut
> +	ItemTable = {}
This is part of the ItemTables PR, please remove from this one.

2023-08-29 23:30 UTC, LordMidas commented on scripts/entity/tactical/enemies/rf_bandit_marauder.nut
> +	    				this.m.Skills.removeByID("actives.rf_bearded_blade");
This removal of Bearded Blade is not reliable. As Bearded Blade is granted by the Axe Mastery perk, if he unequips and then re-equips an axe, he will get the Bearded Blade skill. 

I see you do this in some other entities too.

I currently can't think of a clean way to permanently make Bearded Blade unavailable to an entity, but I can take a look at that once I am back.

2023-08-29 23:30 UTC, LordMidas commented on scripts/entity/tactical/enemies/rf_bandit_outlaw.nut
> +		IsLow = false
This `IsLow` can probably be removed?

2023-08-30 23:31 UTC, LordMidas commented on scripts/entity/tactical/enemies/rf_bandit_marauder.nut
> +	    				this.m.Skills.removeByID("actives.rf_bearded_blade");
I have created an issue (#154) for this and assigned it to myself. Once I am back home I can see how to do that. For now we can merge this in as is.

2023-08-30 23:52 UTC, LordMidas approved these changes
The commit message needs cleanup - then can be merged.

2023-08-31 02:58 UTC, Uberbagel commented
I noticed some errors and made some changes. Please check the most recent commit.

2023-09-11 20:22 UTC, Darxo requested changes

2023-09-11 20:22 UTC, Darxo commented on mod_reforged/hooks/config/global.nut
> +            case ::Const.EntityType.RF_BanditMaruader:
typo

2023-09-11 21:39 UTC, LordMidas approved these changes

2023-09-11 23:59 UTC, Darxo requested changes

2023-09-11 23:59 UTC, Darxo commented on scripts/mods/mod_reforged/dynamic_spawns/units/bandit_units.nut
> +// We adjust the cost of Vanilla units already registered with the Dynamic Spawn Framework:
this comment is no longer necessary. The lines it referenced have been removed

2023-09-12 02:17 UTC, Darxo approved these changes

2023-09-12 02:19 UTC, merged