Feat display ambition icons
Battle-Modders/mod-reforged pull request #170
Opened 2023-09-20 22:45 UTC by Darxo

### Current State

- All Ambitions which can spawn in vanilla now have unique circle-icon associated which are downscaled to 50x50 pixel.
- Those come from Orientation, Backgrounds, Perks, Effects or Traitts; using mostly Vanilla but also some Reforged Artwork
- Duplicate Ambitions which just require a higher number have the same icon. This includes "Do Contracts" and "Do Southern Contracts".
- "Choose No Ambition" has no icon. This is intended

### Remaining Issues:

- Icons which come from Traits have a golden border while all other have a grey border. This may look disconnected.
- Reforged Icons which are used could change any time in the future making them not fit anymore with the Ambitions (same if reforged icons are removed)
- Weapon Mastery Ambition and Named Item Set Ambition currently have the exact same icon of Weapon Master Perk. This is because its a perfect choice for the former ambition while still being a good choice for the latter. And I just couldn't find an alternative for the Named Set one that comes close to Weapon Master Perk

### My Thoughts:

- We should not go as far as to create custom images for Ambitions, not even new ones. I find that a waste of effort for such a minor feature. I'd rather accept that some icons are just acceptable.
- The existing Icons that I chose may also not even be the best choice from the available icons. But we should rather improve these icons over time from player feedback or our own experience ingame.

2023-09-21 16:23 UTC, LordMidas requested changes

2023-09-21 16:23 UTC, LordMidas commented on mod_reforged/hooks/ambitions/ambitions/trade_ambition.nut
> +		create();
Missing icon

2023-10-14 07:09 UTC, Darxo commented
A remaining issue is which Icon we are gonna show for (No Ambition) option and what we are doing for Ambitions from other mods which do not know about this feature.

The solution to those two cases should be part of this PR

2023-10-25 03:06 UTC, Darxo commented
> A remaining issue is which Icon we are gonna show for (No Ambition) option and what we are doing for Ambitions from other mods which do not know about this feature.
> 
> The solution to those two cases should be part of this PR

One solution for this is to not show an icon in those cases. And that behavior already exists in this PR.
I like that solution.

2023-10-31 00:47 UTC, LordMidas commented
> > A remaining issue is which Icon we are gonna show for (No Ambition) option and what we are doing for Ambitions from other mods which do not know about this feature.
> > The solution to those two cases should be part of this PR
> 
> One solution for this is to not show an icon in those cases. And that behavior already exists in this PR. I like that solution.

- For no ambition option, there should be no icon.
- For ambitions without any icon, I think we should have a default icon and that is the golden cup vanilla icon for ambitions. We can create a trait-like icon from that and use that. I can try to prepare one and discuss over at Discord.

2023-11-01 04:49 UTC, LordMidas approved these changes
I think the icon should be placed in `gfx/ui/icons/` folder and not directly in the `gfx/ui/` folder. After that move, consider this approved from my side.

2023-11-01 04:50 UTC, LordMidas commented
You should get rid of the commit that changes the Renown entry, as that feature is implemented already in development in another way.

2023-11-01 04:53 UTC, LordMidas commented on mod_reforged/hooks/ambitions/ambition.nut
> +				local ret = __original();
These changes to `getButtonTooltip` regarding Renown seem to have come into this PR by mistake. Please edit them out.

2023-11-06 00:35 UTC, merged