refactor: port to modern hooks
Battle-Modders/mod-reforged pull request #180
Opened 2023-09-27 20:58 UTC by LordMidas

2023-09-28 01:48 UTC, LordMidas commented on scripts/!mods_preload/mod_reforged.nut
> +::Reforged.HooksMod.queue(function() {
Add manual queue ordering

2023-09-28 01:48 UTC, LordMidas commented on scripts/skills/actives/rf_between_the_eyes_skill.nut
> +			this.m.ActionPointCost += aoq.m.ActionPointCost;
aoo.m.

2023-09-28 01:48 UTC, LordMidas commented on scripts/skills/actives/rf_between_the_eyes_skill.nut
> +		local overlay = aoq.m.Overlay;
aoo.m.

2023-09-28 01:48 UTC, LordMidas commented on scripts/skills/actives/rf_swordmaster_kick_skill.nut
> +		local overlay = aoq.m.Overlay;
aoo.m.

2023-09-28 01:48 UTC, LordMidas commented on scripts/skills/actives/rf_swordmaster_push_through_skill.nut
> +		local overlay = aoq.m.Overlay;
aoo.m.

2023-09-28 01:48 UTC, LordMidas commented on scripts/skills/actives/rf_swordmaster_tackle_skill.nut
> +		local overlay = aoq.m.Overlay;
aoo.m.

2023-10-03 07:16 UTC, Darxo commented on mod_reforged/hooks/entity/tactical/actor.nut
> +		if (verifySettingValue("TacticalTooltip_BagItems")) ret.extend(::Reforged.TacticalTooltip.__originalBagItems(this, 400));
This replacement seems wrong and by accident

2023-10-03 08:08 UTC, Darxo commented on scripts/!mods_preload/mod_reforged.nut
> +::Reforged.HooksMod.queue(">mod_msu", ">mod_dynamic_perks", ">mod_dynamic_spawns", ">mod_item_tables", ">mod_upd", ">mod_stack_based_skills",function() {
missing a space between `,` and `function`

2023-10-03 08:10 UTC, Darxo requested changes
I looked over every single file. Most of them very briefly.

There is just one problem that will likely cause an issue during playtesting.

2023-10-03 20:37 UTC, Darxo approved these changes

2023-10-04 21:29 UTC, merged