Uber Fixes
Battle-Modders/mod-reforged pull request #249
Opened 2023-11-27 23:13 UTC by Uberbagel

2023-11-28 18:26 UTC, LordMidas requested changes

2023-11-28 18:26 UTC, LordMidas commented on scripts/mods/mod_reforged/dynamic_spawns/parties/bandit_parties.nut
These changes don't belong in this PR. Please clean them up.

2023-11-29 10:47 UTC, Uberbagel commented on scripts/mods/mod_reforged/dynamic_spawns/parties/bandit_parties.nut
The branch is titled Uber Fixes and both of these are fixes. If I changed the title of the PR to Fixes would that be okay? I always assumed the PR title defaulted to branch name but I guess that's not the case?

2023-11-29 12:29 UTC, LordMidas commented on scripts/mods/mod_reforged/dynamic_spawns/parties/bandit_parties.nut
I see. Yes then change the PR title. The PR title defaults to the commit message if the PR contains only a single commit at the time it was opened. Otherwise it defaults to the branch name.

2023-11-29 12:30 UTC, LordMidas commented on scripts/mods/mod_reforged/dynamic_spawns/parties/bandit_parties.nut
Also change the commit message of the semi-colon addition to `refactor: add missing semi-colons` because it isn't a fix (semi-colons are optional in squirrel).

2023-11-29 13:46 UTC, LordMidas approved these changes

2023-11-29 13:46 UTC, merged