feat: increase town interaction range while on a caravan mission
Battle-Modders/mod-reforged pull request #265
Opened 2024-02-08 22:43 UTC by Darxo

This is done by replicating the important conditions for this kind of click. 

At the very end, we skip checking for whether player and target are on the same tile and also check for the increased range

2024-03-26 04:41 UTC, LordMidas requested changes
I am not an expert in this, but it looks ok to me. I'd suggest to also request review from @TaroEld.

2024-03-26 04:41 UTC, LordMidas commented on mod_reforged/hooks/config/tip_of_the_day.nut
> +    "You can enter towns while on a caravan mission; even if they are 2 tiles away.",
The semi-colon is wrong here. You can simply remove it and the sentence would be ok.

2024-03-26 04:41 UTC, LordMidas commented on mod_reforged/hooks/states/world_state.nut
> +			local isEscorting = this.m.EscortedEntity != null && !this.m.EscortedEntity.isNull();
Just use `!::MSU.isNull(this.m.EscortedEntity);`

2024-03-26 04:41 UTC, LordMidas commented on mod_reforged/hooks/states/world_state.nut
> +			if (isEscorting && _mouse.getState() == 1 && !this.isInCameraMovementMode() && !this.m.WasInCameraMovementMode)
The `isEscorting` local variable seems unnecessary. You can just put here `if (!::MSU.isNull(this.m.EscortedEntity) && `

2024-03-26 04:41 UTC, LordMidas commented on mod_reforged/hooks/states/world_state.nut
> +					if (entity.isParty()) continue;
I'd also limit the `entity` here to be type of `settlement.nut` so that only actual towns are enterable.

2024-03-26 04:41 UTC, LordMidas commented on mod_reforged/hooks/states/world_state.nut
> +					if (!entity.isAlliedWithPlayer()) continue;
I really think the following looks and reads much better:
```squirrel
if (entity.isParty() || !entity.isEnterable() || !entity.isAlliedWithPlayer())
   continue;
```
than these 3 split very small checks. But it's up to you.

2024-04-02 16:23 UTC, TaroEld commented
LGTM, should work.

2024-04-23 02:32 UTC, LordMidas approved these changes

2024-04-23 02:40 UTC, merged