Rework angler perk and net pull skill
Battle-Modders/mod-reforged pull request #304
Opened 2024-03-23 12:40 UTC by LordMidas

- Increase AP cost of Break Free skill on target by 1.5
- Apply Stagger via Net Pull
- Call useForFree instead of onUse in Net Pull to trigger an actual skill use function call relevant for next point:
- Allow angler to work with free usages of Throw Net (e.g. via net pull)

Also includes 3 bug-fix commits.

2024-03-25 19:07 UTC, Darxo requested changes

2024-03-25 19:07 UTC, Darxo commented on scripts/skills/perks/perk_rf_angler.nut
> +			breakFreeSkill.setBaseValue("ActionPointCost", ::Math.floor(breakFreeSkill.getBaseValue("ActionPointCost") * 1.5));
`1.5` should be a new `this.m.BreakFreeCostMult` instead so that this value is much easier to read out or change by submods.

2024-03-25 20:52 UTC, LordMidas commented on scripts/skills/actives/rf_net_pull_skill.nut
> +			id = 7,
That is a fair point, but also a pain to implement now that we have hundreds of files already coded like this LOL. I'll do it for this one, but for the rest of the files I suggest we make a global commit later that achieves this.

2024-04-13 03:38 UTC, Darxo approved these changes

2024-04-15 20:51 UTC, Darxo approved these changes

2024-04-17 02:07 UTC, merged