refactor: rework dismantle
Battle-Modders/mod-reforged pull request #317
Opened 2024-03-24 10:54 UTC by LordMidas

- Add requirement for Hammer weapon
- Add requirement for Blunt damage type
- Add requirement to hit an actual armor piece
- Add requirement to do at least some armor damage
- Add double the stacks for two-handed hammer
- Clean up conditions in if statement in onTargetHit

2024-03-25 17:35 UTC, Darxo requested changes

2024-04-03 10:46 UTC, LordMidas commented on scripts/skills/perks/perk_rf_dismantle.nut
> +		if (armorPiece == null)
Yes it is intended to only work when hitting an actual armor piece.

2024-04-03 10:47 UTC, LordMidas commented on scripts/skills/perks/perk_rf_dismantle.nut
>  		_targetEntity.getSkills().add(effect);
With skills which are `this.m.IsStacking = false;` adding a skill with the same ID triggers `onRefresh()` function of the skill. That is important as we want to trigger the icon of the effect (look at the `onRefresh()` function in `rf_dismantled_effect.nut`. This is similar logic as the vanilla `overwhelm` perk and its related effect.

2024-04-08 10:58 UTC, Darxo approved these changes

2024-04-11 02:50 UTC, merged