Refactor weapons rebalance
Battle-Modders/mod-reforged pull request #325
Opened 2024-04-02 16:32 UTC by LordMidas

2024-04-03 14:21 UTC, Uberbagel commented on mod_reforged/hooks/items/weapons/barbarians/rusty_warblade.nut
The sheet says 1.1 for Armor Damage Mult. and -18 for stamina as opposed to using the default vanilla value of -16.

2024-04-03 14:31 UTC, Uberbagel commented on scripts/items/weapons/rf_kriegsmesser.nut
Missing 5% chance to hit the head?

2024-04-03 14:34 UTC, Uberbagel requested changes

2024-04-03 14:34 UTC, Uberbagel commented on scripts/items/weapons/rf_reinforced_wooden_poleflail.nut
The skills should have -2 and -5 fat cost respectively

2024-04-19 02:50 UTC, Uberbagel commented on scripts/items/weapons/rf_kriegsmesser.nut
We decided not to add this to the Kriegsmesser

2024-04-20 03:15 UTC, Darxo reviewed
I have no idea if the changes were decided this way. I think this should only be reviewed by bagel

2024-04-21 03:29 UTC, LordMidas commented on scripts/items/weapons/rf_estoc.nut
Now that I think about it maybe we left it off from the estoc to give it another dimension which the regular fencing sword didn't have, because the regular one can attack 3 times with the Fencer perk but the Estoc cannot. So perhaps we made them different like that.

In the rework we have made estoc be higher damage. But I still don't know if the -25% chance to hit the head should be added or not. What do you think?

2024-04-22 08:00 UTC, Uberbagel commented on scripts/items/weapons/rf_estoc.nut
We didn't leave it off of Estoc. I was just questioning if we needed it. I do think Estoc should keep -25% chance to hit the head.

2024-05-14 01:58 UTC, LordMidas commented on mod_reforged/hooks/items/weapons/barbarians/rusty_warblade.nut
We tested it and found out that it's meant to be 1.3 so that is correct.

2024-05-14 02:09 UTC, merged