feat: add combo perk
Battle-Modders/mod-reforged pull request #329
Opened 2024-04-03 12:04 UTC by LordMidas

2024-04-12 18:28 UTC, Darxo requested changes

2024-04-12 18:28 UTC, Darxo commented on scripts/skills/perks/perk_rf_combo.nut
> +		this.m.Description = ::Const.Strings.PerkDescription.RF_Combo;
The perk description is not suited to be the header description of this perk in effect form when viewing the tooltip

2024-04-12 18:28 UTC, Darxo commented on scripts/skills/perks/perk_rf_combo.nut
> +		this.m.UsedSkillID = "";
You do not reset `UsedSkillID` onTurnEnd (as in, this skill is not deactivated then)
That will cause confusion:
- you wonder how long this effect is active after it has not vanished from a character.
- you might be confused by the AP cost of enemy attacks when hovering over them after they ended their turn.

2024-04-12 18:28 UTC, Darxo commented on scripts/skills/perks/perk_rf_combo.nut
> +		this.m.UsedSkillName = "";
It is redundant to reset this variable.

2024-04-13 03:34 UTC, Darxo approved these changes

2024-04-15 04:08 UTC, LordMidas commented
I just realized that one thing missing from this perk is the affordability preview modification. And this is one of those cases where my [improved affordability preview](https://github.com/MSUTeam/MSU/pull/346) implementation over at MSU will be required because we need to check for the `ActionPointCost` of those skills to be above 3 before this skill modifies them.

2024-04-18 18:36 UTC, Darxo approved these changes

2024-04-19 00:49 UTC, Darxo approved these changes

2024-04-19 05:13 UTC, merged