refactor: rework throwing mastery and hybridization
Battle-Modders/mod-reforged pull request #333
Opened 2024-04-03 14:37 UTC by LordMidas

- Move melee skill based hit chance bonus from throwing mastery to Hybridization
- Move damage type based effect application from Hybridization to Throwing Mastery
- Remove increased damage to shields from Throwing Spear from Hybridization

2024-04-08 13:32 UTC, Darxo requested changes

2024-04-08 13:32 UTC, Darxo commented on scripts/skills/perks/perk_rf_hybridization.nut
> +			_properties.RangedSkill += ::Math.floor(this.getContainer().getActor().getCurrentProperties().getMeleeSkill() * 0.2);
The bonus here should be calculated in a separate `getHitchanceBonus()` function.

2024-04-08 13:32 UTC, Darxo commented on scripts/skills/perks/perk_rf_hybridization.nut
> +			_properties.RangedSkill += ::Math.floor(this.getContainer().getActor().getCurrentProperties().getMeleeSkill() * 0.2);
The `0.2` multiplier should be made into a member variable

2024-04-17 19:08 UTC, Darxo approved these changes

2024-04-19 02:45 UTC, Uberbagel requested changes
Hybridization is supposed to allow swapping to or from a throwing weapon to cost 0 AP once per turn. This is not accounted for in the code or tooltips at this time.

2024-04-20 03:12 UTC, Darxo requested changes

2024-04-20 03:12 UTC, Darxo commented on scripts/skills/perks/perk_rf_hybridization.nut
> +		foreach (item in _items)
You need to check whether `this.m.IsSpent` is `true` and then return early with null.
Otherwise you can swap endlessly in a turn.

2024-04-20 03:12 UTC, Darxo commented on scripts/skills/perks/perk_rf_hybridization.nut
> +		IsSpent = false,
If you set this to `true` whenever a combat ends then you probably also want it `true` by default, so this perk is never visible outside of battle.

2024-04-22 06:47 UTC, merged