refactor: grant -1 reach with tiny trait
Battle-Modders/mod-reforged pull request #343
Opened 2024-04-04 03:29 UTC by LordMidas

To be in line with the Huge trait which grants +1 Reach.

2024-04-06 02:36 UTC, Uberbagel reviewed
We should also change the damage reduction to 10% instead of 15%, also to be in line with Tough.

2024-04-08 09:35 UTC, Darxo requested changes

2024-04-09 09:46 UTC, LordMidas commented on mod_reforged/hooks/skills/traits/tiny_trait.nut
> +			id = ret.top().id + 1,
Yes I thought of this too and was expecting your comment on this. You are correct, we should just apply a fixed id here. It is difficult however to ensure in these functions that our id will be unique as different perks/skills can modify the tooltip in this `onQueryTooltip` function. So, maybe we can just use a very unique id such as `1001`.

2024-04-11 05:48 UTC, Darxo commented
> We should also change the damage reduction to 10% instead of 15%, also to be in line with Tough.

I agree with this, but not just "to be in line".
Rather Tiny is even worse in melee now with the -1 Reach and the intention of that change was not to nerf its melee capability further. Reduction the damage-debuff is the most sensible way to keep the trait similar in power

2024-04-11 17:54 UTC, Darxo approved these changes

2024-04-11 18:56 UTC, merged