Enemy rebalance
Battle-Modders/mod-reforged pull request #362
Opened 2024-04-25 20:54 UTC by Uberbagel

Requires new perks to be merged before testable.

2024-05-02 02:26 UTC, LordMidas requested changes

2024-05-02 02:26 UTC, LordMidas commented on scripts/entity/tactical/enemies/rf_bandit_marauder.nut
You never set `this.m.MyVariant` to any value during `onInit`.

2024-05-02 02:26 UTC, LordMidas commented on scripts/entity/tactical/enemies/rf_bandit_outlaw.nut
You never set `this.m.MyVariant` to any value during `onInit`.

2024-05-02 13:29 UTC, Darxo reviewed
I wish there were more comments in the commits that explained what changed, even if its just on a surface level.
That is important for a reviewer to know whether the changes you did reflect your intentions aswell as whether there is a balance concern with your proposed changes.

The only thing I remember from being told in person is that you raised the hitpoints of several enemies.

2024-05-03 08:53 UTC, Uberbagel commented on mod_reforged/hooks/config/spawnlist_master.nut
> +::Const.World.Spawn.Troops.SkeletonLight.Cost = 12;
yes

2024-05-03 08:53 UTC, Uberbagel commented on mod_reforged/hooks/config/spawnlist_master.nut
> +::Const.World.Spawn.Troops.BanditRaider.Strength = 28;
yes

2024-05-03 08:55 UTC, Uberbagel commented on mod_reforged/hooks/entity/tactical/humans/barbarian_madman.nut
> +	// q.assignRandomEquipment = @(__original) function()
Sanguinary is pointless on him as it's a 1v1 fight. I believe I didn't give Mauler because with his other perks it was overwhelming.

2024-05-03 09:12 UTC, Uberbagel commented
> I wish there were more comments in the commits that explained what changed, even if its just on a surface level. That is important for a reviewer to know whether the changes you did reflect your intentions aswell as whether there is a balance concern with your proposed changes. The only thing I remember from being told in person is that you raised the hitpoints of several enemies.
> 
> As of right now the best thing I can do is check for missing commas and semicolons. Maybe its better if Midas does the reviewing by himself

Most of the design discussions were done in voice to confirm direction and if I was accomplishing what I was intending too. You and I actually did have one of these discussions before Midas and I did for these enemy changes. We talked about Bandits and Nobles for sure, and I would assume the Ancient Dead as well. You signed off on the general direction of my changes and said you didn't want/need to be present for the deeper review.

2024-05-03 19:05 UTC, Darxo commented
That was 1+ month ago. By now I've forgotten most of what we talked about.
Without any notes I am not able to confirm whether the changes in the code achieve what you want to do.
For the patch notes you will need some notes anyways so it's not like it's extra work to do them now.

If Midas doesn't need those then dismiss this request and I will just not review this PR.

2024-05-15 10:21 UTC, LordMidas approved these changes

2024-05-15 17:08 UTC, merged