feat: add more southern names and extend last names using basic names
Battle-Modders/mod-reforged pull request #425
Opened 2024-06-08 01:53 UTC by LordMidas

This adds more variety for southern names:
- Add 59 new names.
- Extend the vanilla "southern last names" list by prefixing `Ibn` and `Al-` to all the first names.

2024-06-08 04:56 UTC, Uberbagel commented
> Extend the vanilla "southern last names" list by prefixing Ibn and Al- to all the first names.

Can you explain what this means in practical terms?

2024-06-08 06:44 UTC, LordMidas commented
> > Extend the vanilla "southern last names" list by prefixing Ibn and Al- to all the first names.
> 
> Can you explain what this means in practical terms?

`Ibn` means "son of` and `Al-` means "the" in Arabic. Vanilla has two lists `SouthernNames` and `SouthernNamesLast`. It generates characters by using a name from `SouthernNames` and then sometimes it affixes a last name from `SouthernNamesLast`. These last names in vanilla are composed of formations such as `Ibn Sahr` or `Al-Faris`. I think there is no reason why can't expand that setup by just prefixing `Ibn` and `Al-` to all the first names. This results in a lot more possible valid last names.

2024-06-08 22:30 UTC, Uberbagel commented
So now we lose Ibn Sahr and Al-Faris and only get Ibn Al-???

2024-06-09 01:15 UTC, LordMidas commented
> So now we lose Ibn Sahr and Al-Faris and only get Ibn Al-???

No. We extend the last names list by prefixing Ibn and Al- to all the first names. So if a first name was "Adil" for example then both "Ibn Adil" and "Al-Adil" are now additional valid last names to roll from.

2024-06-09 09:00 UTC, Darxo requested changes

2024-06-09 09:00 UTC, Darxo commented on mod_reforged/hooks/config/character_names.nut
> +}
The name `Wasi` appears in `SouthernNames` and also in `SouthernNamesLast`. There might be more name overlaps.
Furthermore as described above, two names appear twice in the list bove.

You should remove duplicates after generating this name list, like we do above with the knight names

2024-06-09 21:10 UTC, Uberbagel commented
Sounds good then

2024-06-09 21:11 UTC, Uberbagel approved these changes

2024-06-10 00:31 UTC, Darxo approved these changes

2024-07-21 18:14 UTC, Darxo approved these changes

2024-07-21 22:35 UTC, Uberbagel approved these changes

2024-07-22 03:30 UTC, merged