balance: add soul link to necromancer
Battle-Modders/mod-reforged pull request #498
Opened 2024-09-04 21:33 UTC by Uberbagel

Because with Take Aim now being given with crossbow mastery, it makes sniping them too easy without this change.

2024-09-05 08:49 UTC, Darxo approved these changes
I wish the

2024-09-06 04:24 UTC, LordMidas requested changes

2024-09-06 04:24 UTC, LordMidas commented on mod_reforged/hooks/entity/tactical/enemies/necromancer.nut
> +		this.m.Skills.add(::new("scripts/skills/perks/perk_rf_soul_link"));
Should be moved down to the section that is marked with the `//Reforged` comment.

2024-09-06 08:39 UTC, Darxo approved these changes

2024-09-07 00:06 UTC, LordMidas approved these changes

2024-09-07 00:56 UTC, merged