balance: adjust nomad spawns
Battle-Modders/mod-reforged pull request #515
Opened 2024-09-13 23:14 UTC by Uberbagel

reduce strength and cost of nomad outlaw
set startingresourcemin of nomad leader to 250

2024-09-14 00:47 UTC, Darxo requested changes

2024-09-14 00:47 UTC, Darxo commented on mod_reforged/hooks/config/spawnlist_master.nut
> +::Const.World.Spawn.Troops.NomadOutlaw.Strength = 20;
Two times the same line

2024-09-15 05:21 UTC, Uberbagel commented on mod_reforged/hooks/config/spawnlist_master.nut
> +::Const.World.Spawn.Troops.NomadOutlaw.Strength = 20;
should've noticed that...

2024-09-15 08:34 UTC, Darxo approved these changes

2024-09-15 09:06 UTC, LordMidas requested changes

2024-09-15 09:06 UTC, LordMidas commented on mod_reforged/hooks/config/spawnlist_master.nut
> +::Const.World.Spawn.Troops.NomadOutlaw.Strength = 20;
Please mention the vanilla cost/strength as a comment next to these changes.

2024-09-15 09:06 UTC, LordMidas commented on mod_reforged/hooks/config/spawnlist_master.nut
Would be nice to have an overview of the design intention behind these changes. My inference is that this will make Outlaws appear sooner, and Leaders appear later. But isn't the south meant to spawn leaders earlier? This seems to go against that design of that faction.

2024-09-16 01:03 UTC, Uberbagel commented on mod_reforged/hooks/config/spawnlist_master.nut
Your inference is correct. I didn't know/remember that leaders spawning earlier was our design intention for Nomads. Nomad Leaders aren't any weaker than Bandit Leaders. They would be comparable if not a little better than Bandit Leaders if not for their armor/helmet being able to lowroll. I'm drop their starting resource min to 200 instead of 250, so they will come earlier than bandit leaders and match this design of Nomad Leaders spawning earlier, but I think going below 200 would be a mistake. Bandit Leaders are 250 for comparison.

2024-09-16 01:04 UTC, Uberbagel commented on mod_reforged/hooks/config/spawnlist_master.nut
And the Outlaw changes are necessary because currently they start showing up way too late and i did a strength comparison with bandits and I think 20 is reasonable for them.

2024-09-16 01:19 UTC, LordMidas commented on mod_reforged/hooks/config/spawnlist_master.nut
We had a VC where we compared the spawns to bandits and we realized that Nomad Leaders spawn in roughly similar parties as Bandit party compositions. But we decided to go with 200 cost on Nomad Leaders to give them a bit of thematic difference. Also the Outlaw cost change seems reasonable considering their strength and upgrading in Dynamic Spawns so let's see how it plays it.

2024-09-16 01:52 UTC, LordMidas approved these changes

2024-09-16 01:52 UTC, merged