Remove hooks on inherited backgrounds
Battle-Modders/mod-reforged pull request #551
Opened 2024-10-04 00:41 UTC by LordMidas

- Fixes the issue that shepherd southern gets the bonuses twice.
- I've taken the opportunity to remove hooks on other southern backgrounds where identical changes were present in our hook on the parent background. While in these cases it was benign, but it's still good to remove these.
- Please ensure that everything that I've removed is correct (i.e. identical hook exists on parent background) and let me know if I've missed any. 

@Uberbagel I haven't touched the 3 different slave backgrounds in this PR. Please take a look at them in Reforged and notice that they have slightly different multipliers for perk groups. Let me know if that is intended.

2024-10-04 10:17 UTC, Darxo approved these changes

2024-10-04 12:56 UTC, Uberbagel commented
> @Uberbagel I haven't touched the 3 different slave backgrounds in this PR. Please take a look at them in Reforged and notice that they have slightly different multipliers for perk groups. Let me know if that is intended.

Three different Slaves are intended, yes.

2024-10-04 13:03 UTC, Uberbagel requested changes
Missed Southern Peddler

2024-10-05 01:02 UTC, Uberbagel approved these changes

2024-10-05 01:02 UTC, merged