feat: add mod setting to control visibility of blueprints in taxidermist
Battle-Modders/mod-reforged pull request #560
Opened 2024-10-13 03:44 UTC by Darxo

**Always** treats all Blueprints in the game as if you've already crafted them once before
**One Ingredient Available** treats all Blueprints in the game, for which you have at least one Ingredient, as if you've already crafted them once before
**All Ingredient Available** treats all Blueprints in the game, as if you've never crafted them once before
**Vanilla** applies the Vanilla filtering behavior

This hook preserves any overwritten Qualified-behavior like that of Snake Oil. 
Those recipes will not show up, no matter what setting is active, if those overwritten rules forbid it.

2024-11-26 18:43 UTC, Uberbagel approved these changes

2024-12-07 13:18 UTC, TaroEld requested changes

2024-12-07 13:18 UTC, TaroEld commented on mod_reforged/hooks/crafting/crafting_manager.nut
> +		return __original();
Move this return statement into the Vanilla case, and move it up top as the first option. This makes it clearer that on the "Vanilla" setting, we just run the original function.
Also add a default: case where you throw with a message that the case was not recognized. This is a failsave against future regressions.

2024-12-11 07:41 UTC, TaroEld approved these changes
I'd still like to see a default {throw "Unknown argument"} case.

2024-12-13 08:12 UTC, merged