fix: add safety check for skill containers before spinning the flail
Battle-Modders/mod-reforged pull request #567
Opened 2024-10-18 17:41 UTC by Darxo

In a recent bug report the user crashed when a Fallen Hero spun the flail.
According to the log it looks like the Fallen Hero died to Riposte/Rebuke while spinning the flail.

![image](https://github.com/user-attachments/assets/70d062cd-cb3f-48a5-a488-a819214879d7)

If a dying actor instantly uncoupled from its skill container and/or deconstructs its actor object then that would explain, why we crash during the `onVerifyTarget` function.
That function assumes this skill to be attached to a skill container and that container to be attached to an actor.

![image](https://github.com/user-attachments/assets/99b5131d-b60d-46e2-aa17-3cbd83305c38)

My solution is to check for the coupling of the container before spinning the flail

2025-03-04 15:23 UTC, LordMidas requested changes

2025-03-04 15:23 UTC, LordMidas commented on scripts/skills/perks/perk_rf_flail_spinner.nut
> +			}
This might be too early for this check. I think this should be moved into the scheduled event inside `spinFlail` because a counter-attack usually happens with a delay.

2025-03-11 04:16 UTC, Darxo commented on scripts/skills/perks/perk_rf_whirling_death.nut
> +				if (user.isAlive() && target.isAlive())
What do you make of the vanilla check `!actor.isDying()`, which I constantly see alongside the `isAlive` check?
Is it redundant, or just not needed in this particular case?
I dont know the difference/nuance between those two checks

2025-03-11 04:51 UTC, LordMidas commented on scripts/skills/perks/perk_rf_whirling_death.nut
> +				if (user.isAlive() && target.isAlive())
I have not looked into it in maximum detail but as far as I looked the `IsDying = true` is set during `actor.kill` function slightly before `IsAlive = false`. So, it seems it is only relevant for certain skill events e.g. `onDeath` where `IsDying` will be true but `IsAlive` will be false.

For our use case here I used to do both `isAlive` and `isDying` checks following some vanilla style, but eventually I realized that the doing `isAlive` is enough. In my opinion the `isDying` check would be redundant and I have so far never encountered any issue in skipping it in skill_container events.

Vanilla also only checks for `target.isAlive()` in the delayed attacks from `cascade_skill.onUse`, so maybe for these cases the `isAlive` check is enough.

2025-03-11 06:44 UTC, LordMidas approved these changes

2025-03-11 06:44 UTC, merged